### PR TITLE
feat: update profile readme

### LINKED ISSUE #18: Update Profile README
## Motivation

Refresh the main Pact Foundation [profile README](https://github.com/pact-foundation/.github/tree/master/PROFILE).

## Suggested Changes

1. **Incorporate Pact Summary**

   A nice Pact summary exists for [Pact Python](https://github.com/pact-foundation/pact-python), [Pact PHP](https://github.com/pact-foundation/pact-php), [Pact JS](https://github.com/pact-foundation/pact-js), [Pact Go](https://github.com/pact-foundation/pact-go). It would be could to repeat the consistency with the front page too.

2. **Superfluous Stats**

   Some of the stats are, in my opinion, not too useful. In particular, I would suggest:

   1. Removing the "Joined GitHub", number of members and location
   2. removing most of the repository stats, only keeping the stargazers, forkers and watchers.
   3. Change the issues and PR stats to use the last 3 months only
   4. Remove 'most used languages' stats (it is dominated by HTML anyway)
   5. Remove recent activity (this can be seen from the activity sparklines next to each repo)
   6. Remove achievements (do we care that the Pact Foundation is a polyglot?)

3. Table of supported languages

   Open to feedback on this one, but I'm thinking of adding a table of language logos linking to the relevant Pact repository. This would hopefully make it easier for people to discover the Pact implementation they care about quite quickly.

### PR DESCRIPTION
**Pull request by JP-Ellis**
Resolves #18 

Note: Do _not_ merge as it is. The GitHub action is set up to trigger on this PR, which is required in order to showcase a preview of the new stats page, but is not intended long term.

### CODE REVIEW

**Comment by YOU54F** [comment]
> Note: Do not merge as it is. The GitHub action is set up to trigger on this PR, which is required in order to showcase a preview of the new stats page, but is not intended long term.

Do you just want to remove the stats image?

**Review by YOU54F — APPROVED** [review]
Woop woop the consistency with several of the pact repos make me very happy

happy if the metrics svg and job get removed

**Comment by JP-Ellis** [comment]
I reduced the metrics to be much much smaller, just I guess it isn't really necessary. The only thing to keep maybe is the list of members/contributors? Do you think that's worth advertising? Or better just do that with each repo?

**Comment by YOU54F** [comment]
> I reduced the metrics to be much much smaller, just I guess it isn't really necessary. The only thing to keep maybe is the list of members/contributors? Do you think that's worth advertising? Or better just do that with each repo?

hmm, the pictures can't be clicked on, and we can see them via the teams tab if a user wished to. I'm okay either way, also happy with the reduced metrics as proposed in the repo, although they probably aren't relevant to users or actionable (non clickable, so possibly of questionable value)

From our cursory glance at a few high profile orgs, many of the profiles were very [lean](https://github.com/microsoft) , or non-existent [redhat](https://github.com/RedHatOfficial)/[facebook](https://github.com/facebook)

**Comment by JP-Ellis** [comment]
You're right, I've removed the metrics SVG and corresponding workflow 👍

**Pull request merged**
